-- !!!                                                                                           !!!
-- !!!            DO NOT EVER ACCIDENTALLY RUN THIS FILE IN YOUR PRODUCTION DATABASE             !!!
-- !!!    this is meant for running locally to seed your database for contributing purposes      !!!

-- P.S. These data maybe a little bit werid, is is generated by AI model, just for basic test ;)

-- artist@rearyard.com / password
INSERT INTO auth.users (instance_id, id, aud, role, email, encrypted_password, email_confirmed_at, recovery_sent_at,
                        last_sign_in_at, raw_app_meta_data, raw_user_meta_data, created_at, updated_at,
                        confirmation_token, email_change, email_change_token_new, recovery_token)
VALUES ('00000000-0000-0000-0000-000000000000', uuid_generate_v4(), 'authenticated', 'authenticated',
        'artist@rearyard.com', crypt('password', gen_salt('bf')), current_timestamp, current_timestamp, current_timestamp,
        '{"provider":"email","providers":["email"]}', '{}', current_timestamp, current_timestamp, '', '', '', '');

-- reader@rearyard.com / password
INSERT INTO auth.users (instance_id, id, aud, role, email, encrypted_password, email_confirmed_at, recovery_sent_at,
                        last_sign_in_at, raw_app_meta_data, raw_user_meta_data, created_at, updated_at,
                        confirmation_token, email_change, email_change_token_new, recovery_token)
VALUES ('00000000-0000-0000-0000-000000000000', uuid_generate_v4(), 'authenticated', 'authenticated',
        'reader@rearyard.com', crypt('password', gen_salt('bf')), current_timestamp, current_timestamp, current_timestamp,
        '{"provider":"email","providers":["email"]}', '{}', current_timestamp, current_timestamp, '', '', '', '');

-- editor@rearyard.com / password
INSERT INTO auth.users (instance_id, id, aud, role, email, encrypted_password, email_confirmed_at, recovery_sent_at,
                        last_sign_in_at, raw_app_meta_data, raw_user_meta_data, created_at, updated_at,
                        confirmation_token, email_change, email_change_token_new, recovery_token)
VALUES ('00000000-0000-0000-0000-000000000000', uuid_generate_v4(), 'authenticated', 'authenticated',
        'editor@rearyard.com', crypt('password', gen_salt('bf')), current_timestamp, current_timestamp, current_timestamp,
        '{"provider":"email","providers":["email"]}', '{}', current_timestamp, current_timestamp, '', '', '', '');

-- translator@rearyard.com / password
INSERT INTO auth.users (instance_id, id, aud, role, email, encrypted_password, email_confirmed_at, recovery_sent_at,
                        last_sign_in_at, raw_app_meta_data, raw_user_meta_data, created_at, updated_at,
                        confirmation_token, email_change, email_change_token_new, recovery_token)
VALUES ('00000000-0000-0000-0000-000000000000', uuid_generate_v4(), 'authenticated', 'authenticated',
        'translator@rearyard.com', crypt('password', gen_salt('bf')), current_timestamp, current_timestamp, current_timestamp,
        '{"provider":"email","providers":["email"]}', '{}', current_timestamp, current_timestamp, '', '', '', '');

-- reviewer@rearyard.com / password
INSERT INTO auth.users (instance_id, id, aud, role, email, encrypted_password, email_confirmed_at, recovery_sent_at,
                        last_sign_in_at, raw_app_meta_data, raw_user_meta_data, created_at, updated_at,
                        confirmation_token, email_change, email_change_token_new, recovery_token)
VALUES ('00000000-0000-0000-0000-000000000000', uuid_generate_v4(), 'authenticated', 'authenticated',
        'reviewer@rearyard.com', crypt('password', gen_salt('bf')), current_timestamp, current_timestamp, current_timestamp,
        '{"provider":"email","providers":["email"]}', '{}', current_timestamp, current_timestamp, '', '', '', '');

-- add email identities for all test users
INSERT INTO auth.identities (id, user_id, identity_data, provider, provider_id, last_sign_in_at, created_at, updated_at)
SELECT 
    uuid_generate_v4(),
    users.id,
    format('{"sub":"%s","email":"%s"}', users.id::text, users.email)::jsonb,
    'email',
    uuid_generate_v4(),
    current_timestamp,
    current_timestamp,
    current_timestamp
FROM auth.users
WHERE email LIKE '%@rearyard.com';

-- add user_basic information for test users
INSERT INTO public.user_basic (user_id, nickname, signature, avatar)
SELECT 
    id as user_id,
    CASE 
        WHEN email = 'artist@rearyard.com' THEN '画师小A'
        WHEN email = 'reader@rearyard.com' THEN '爱读书的小R'
        WHEN email = 'editor@rearyard.com' THEN '编辑小E'
        WHEN email = 'translator@rearyard.com' THEN '翻译小T'
        WHEN email = 'reviewer@rearyard.com' THEN '评论家小V'
        WHEN email = 'writer@rearyard.com' THEN '作家小W'
    END as nickname,
    CASE 
        WHEN email = 'artist@rearyard.com' THEN '用画笔描绘美好的世界'
        WHEN email = 'reader@rearyard.com' THEN '阅读是一场美妙的旅行'
        WHEN email = 'editor@rearyard.com' THEN '让每一个作品都闪耀光芒'
        WHEN email = 'translator@rearyard.com' THEN '连接不同语言的桥梁'
        WHEN email = 'reviewer@rearyard.com' THEN '用专业的眼光发现精彩'
        WHEN email = 'writer@rearyard.com' THEN '用文字编织梦想'
    END as signature,
    CASE 
        WHEN email = 'artist@rearyard.com' THEN 'https://api.dicebear.com/7.x/avataaars/svg?seed=artist'
        WHEN email = 'reader@rearyard.com' THEN 'https://api.dicebear.com/7.x/avataaars/svg?seed=reader'
        WHEN email = 'editor@rearyard.com' THEN 'https://api.dicebear.com/7.x/avataaars/svg?seed=editor'
        WHEN email = 'translator@rearyard.com' THEN 'https://api.dicebear.com/7.x/avataaars/svg?seed=translator'
        WHEN email = 'reviewer@rearyard.com' THEN 'https://api.dicebear.com/7.x/avataaars/svg?seed=reviewer'
        WHEN email = 'writer@rearyard.com' THEN 'https://api.dicebear.com/7.x/avataaars/svg?seed=writer'
    END as avatar
FROM auth.users
WHERE email LIKE '%@rearyard.com';

-- Create Harry Potter fandom
WITH editor_user AS (
    SELECT user_id 
    FROM public.user_basic 
    WHERE nickname = '编辑小E'
)
INSERT INTO public.fandom (name, created_by, is_official_managed)
SELECT 
    '哈利·波特',
    user_id,
    true
FROM editor_user
RETURNING id AS fandom_id;

-- Insert Harry Potter characters
WITH hp_fandom AS (
    SELECT id AS fandom_id 
    FROM public.fandom 
    WHERE name = '哈利·波特'
),
editor_user AS (
    SELECT user_id 
    FROM public.user_basic 
    WHERE nickname = '编辑小E'
)
INSERT INTO public.character (name, created_by, fandom_id)
SELECT 
    character_name,
    editor_user.user_id,
    hp_fandom.fandom_id
FROM (
    VALUES 
        ('哈利·波特'),
        ('赫敏·格兰杰'),
        ('罗恩·韦斯莱'),
        ('阿不思·邓布利多'),
        ('西弗勒斯·斯内普'),
        ('伏地魔'),
        ('德拉科·马尔福'),
        ('卢娜·洛夫古德'),
        ('纳威·隆巴顿'),
        ('小天狼星·布莱克'),
        ('莱姆斯·卢平'),
        ('金妮·韦斯莱'),
        ('弗雷德·韦斯莱'),
        ('乔治·韦斯莱'),
        ('多比')
) AS characters(character_name)
CROSS JOIN hp_fandom
CROSS JOIN editor_user;

-- Insert Harry Potter relations
WITH hp_fandom AS (
    SELECT id AS fandom_id 
    FROM public.fandom 
    WHERE name = '哈利·波特'
),
reader_user AS (
    SELECT user_id 
    FROM public.user_basic 
    WHERE nickname = '爱读书的小R'
),
hp_characters AS (
    SELECT id, name
    FROM public.character
    WHERE fandom_id = (SELECT fandom_id FROM hp_fandom)
)
INSERT INTO public.relation (name, created_by, fandom_ids, characters)
SELECT 
    relation_name,
    reader_user.user_id,
    ARRAY[hp_fandom.fandom_id],
    ARRAY(
        SELECT id 
        FROM hp_characters 
        WHERE name = ANY(character_names)
        ORDER BY ARRAY_POSITION(character_names, name)
    )
FROM (
    VALUES 
        -- 爱情关系
        ('挚爱', ARRAY['哈利·波特', '金妮·韦斯莱']),
        ('初恋', ARRAY['金妮·韦斯莱', '哈利·波特']), -- 测试不同顺序
        ('最佳CP', ARRAY['罗恩·韦斯莱', '赫敏·格兰杰']),
        ('暗恋', ARRAY['西弗勒斯·斯内普', '莉莉·波特']),

        -- 友情关系
        ('黄金三人组', ARRAY['哈利·波特', '赫敏·格兰杰', '罗恩·韦斯莱']),
        ('三人组的友谊', ARRAY['罗恩·韦斯莱', '哈利·波特', '赫敏·格兰杰']), -- 测试不同顺序
        ('韦斯莱双子', ARRAY['弗雷德·韦斯莱', '乔治·韦斯莱']),
        ('双子组合', ARRAY['乔治·韦斯莱', '弗雷德·韦斯莱']), -- 测试不同顺序

        -- 师生关系
        ('校长与学生', ARRAY['阿不思·邓布利多', '哈利·波特']),
        ('严厉的教授', ARRAY['西弗勒斯·斯内普', '哈利·波特']),

        -- 对立关系
        ('宿敌', ARRAY['哈利·波特', '伏地魔']),
        ('死敌', ARRAY['伏地魔', '哈利·波特']), -- 测试不同顺序
        ('学院对头', ARRAY['哈利·波特', '德拉科·马尔福']),
        ('校园死对头', ARRAY['德拉科·马尔福', '哈利·波特']), -- 测试不同顺序

        -- 守护关系
        ('忠诚的家养小精灵', ARRAY['多比', '哈利·波特']),
        ('教父子关系', ARRAY['小天狼星·布莱克', '哈利·波特']),
        
        -- 战友关系
        ('DA核心成员', ARRAY['哈利·波特', '纳威·隆巴顿', '卢娜·洛夫古德']),
        ('凤凰社战友', ARRAY['莱姆斯·卢平', '小天狼星·布莱克'])
) AS relations(relation_name, character_names)
CROSS JOIN hp_fandom
CROSS JOIN reader_user;

-- Insert follow relationships
WITH users AS (
    SELECT ub.user_id, ub.nickname, au.email
    FROM public.user_basic ub
    JOIN auth.users au ON ub.user_id = au.id
    WHERE ub.nickname IN ('画师小A', '爱读书的小R', '编辑小E', '翻译小T', '评论家小V', '作家小W')
)
INSERT INTO public.follow (follower_id, following_id)
SELECT DISTINCT follower.user_id, following.user_id
FROM (
    VALUES 
        -- 作家和编辑互相关注
        ('作家小W', '编辑小E'),
        ('编辑小E', '作家小W'),
        
        -- 画师和翻译互相关注
        ('画师小A', '翻译小T'),
        ('翻译小T', '画师小A'),
        
        -- 读者关注所有人
        ('爱读书的小R', '作家小W'),
        ('爱读书的小R', '编辑小E'),
        ('爱读书的小R', '画师小A'),
        ('爱读书的小R', '翻译小T'),
        ('爱读书的小R', '评论家小V'),
        
        -- 评论家被所有人关注
        ('作家小W', '评论家小V'),
        ('编辑小E', '评论家小V'),
        ('画师小A', '评论家小V'),
        ('翻译小T', '评论家小V'),
        
        -- 作家和画师互相关注（创作者联盟）
        ('作家小W', '画师小A'),
        ('画师小A', '作家小W'),
        
        -- 编辑和翻译互相关注（校对联盟）
        ('编辑小E', '翻译小T'),
        ('翻译小T', '编辑小E')
) AS follows(follower_nickname, following_nickname)
JOIN users follower ON follower.nickname = follows.follower_nickname
JOIN users following ON following.nickname = follows.following_nickname
WHERE follower.user_id != following.user_id; -- 额外的安全检查，防止自我关注

-- Insert tags
WITH users AS (
    SELECT user_id, nickname
    FROM public.user_basic
    WHERE nickname IN ('画师小A', '爱读书的小R', '编辑小E', '翻译小T', '评论家小V', '作家小W')
)
INSERT INTO public.tag (name)
SELECT DISTINCT tag_name
FROM (
    VALUES 
        -- 编辑小E创建的基础分类标签
        ('原创'), ('同人'), ('连载'), ('完结'), ('短篇'), ('中篇'), ('长篇'),
        ('悬疑'), ('冒险'), ('浪漫'), ('喜剧'), ('悲剧'), ('治愈'),
        
        -- 作家小W创建的写作技巧相关标签
        ('第一人称'), ('第三人称'), ('意识流'), ('倒叙'), ('插叙'), ('双线叙事'),
        ('独白'), ('对话'), ('心理描写'), ('环境描写'),
        
        -- 画师小A创建的画风标签
        ('水彩'), ('素描'), ('油画'), ('插画'), ('漫画'), ('像素画'),
        ('写实'), ('抽象'), ('赛博朋克'), ('魔幻'),
        
        -- 翻译小T创建的翻译相关标签
        ('英译中'), ('中译英'), ('意译'), ('直译'), ('本地化'),
        
        -- 评论家小V创建的评价标签
        ('经典'), ('创新'), ('精品'), ('佳作'), ('新人作品'), ('热门'),
        ('争议'), ('小众'), ('实验性'), ('前卫'),
        
        -- 爱读书的小R创建的哈利波特相关标签
        ('魔法'), ('魁地奇'), ('霍格沃茨'), ('格兰芬多'), ('斯莱特林'),
        ('赫奇帕奇'), ('拉文克劳'), ('魔杖'), ('魔咒'), ('魔药'),
        ('黑魔法防御术'), ('魔法部'), ('阿兹卡班'), ('死亡圣器'),
        ('活点地图'), ('冥想盆'), ('守护神'), ('魂器'),
        
        -- 通用情节标签
        ('友情'), ('亲情'), ('爱情'), ('成长'), ('冒险'), ('战斗'),
        ('校园'), ('日常'), ('奇幻'), ('青春'), ('励志')
) AS tags(tag_name);

-- Create some works
WITH hp_fandom AS (
    SELECT id AS fandom_id 
    FROM public.fandom 
    WHERE name = '哈利·波特'
),
hp_characters AS (
    SELECT id, name
    FROM public.character
    WHERE fandom_id = (SELECT fandom_id FROM hp_fandom)
),
hp_relations AS (
    SELECT id, name
    FROM public.relation
    WHERE fandom_ids @> ARRAY[(SELECT fandom_id FROM hp_fandom)]
),
users AS (
    SELECT user_id, nickname
    FROM public.user_basic
    WHERE nickname IN ('画师小A', '爱读书的小R', '编辑小E', '翻译小T', '评论家小V', '作家小W')
)
INSERT INTO public.work (
    title,
    description,
    type,
    fandoms,
    characters,
    relationships,
    created_by
)
SELECT 
    w.title,
    w.description,
    w.work_type::public.work_type,
    ARRAY[(SELECT fandom_id FROM hp_fandom)],
    ARRAY(
        SELECT id 
        FROM hp_characters 
        WHERE name = ANY(w.character_names)
    ),
    ARRAY(
        SELECT id 
        FROM hp_relations 
        WHERE name = ANY(w.relation_names)
    ),
    u.user_id
FROM (
    VALUES 
        -- 作家小W的作品
        ('作家小W', 
         '霍格沃茨的新学期', 
         '开学第一天，哈利和他的朋友们又回到了霍格沃茨。然而，一个神秘的转学生的到来，让这个学期变得不同寻常...', 
         'series',
         ARRAY['哈利·波特', '罗恩·韦斯莱', '赫敏·格兰杰'],
         ARRAY['黄金三人组'],
         ARRAY['魔法', '霍格沃茨', '友情', '冒险']::varchar[]),
         
        -- 画师小A的作品
        ('画师小A',
         '魔法世界的日常', 
         '一组关于霍格沃茨日常生活的插画集，包括上课、魁地奇训练、公共休息室等场景。',
         'post',
         ARRAY['哈利·波特', '德拉科·马尔福'],
         ARRAY['学院对头'],
         ARRAY['魁地奇', '霍格沃茨', '日常']::varchar[]),
         
        -- 翻译小T的作品
        ('翻译小T',
         '魔药学笔记', 
         '斯内普教授的魔药课堂笔记，包含了详细的魔药配方和注意事项。',
         'passage',
         ARRAY['西弗勒斯·斯内普', '哈利·波特'],
         ARRAY['严厉的教授'],
         ARRAY['魔药', '霍格沃茨']::varchar[]),
         
        -- 爱读书的小R的作品
        ('爱读书的小R',
         '守护神物语', 
         '关于不同人物的守护神是如何选择他们的，一个充满温情的故事集。',
         'series',
         ARRAY['哈利·波特', '卢娜·洛夫古德', '纳威·隆巴顿'],
         ARRAY['DA核心成员'],
         ARRAY['守护神', '治愈', '成长']::varchar[])
) AS w(
    creator_nickname,
    title,
    description,
    work_type,
    character_names,
    relation_names,
    tag_names
)
JOIN users u ON u.nickname = w.creator_nickname
RETURNING id, title, type, created_by;

-- Insert content for each work
WITH work_info AS (
    SELECT w.id AS work_id, w.title AS work_title, w.type, u.nickname AS creator_nickname
    FROM public.work w
    JOIN public.user_basic u ON w.created_by = u.user_id
    WHERE w.created_at >= (SELECT MAX(created_at) FROM public.work) -- 只获取刚刚创建的作品
),
tag_ids AS (
    SELECT id, name FROM public.tag
)
INSERT INTO public.content (
    work_id,
    work_title,
    plain_text,
    schema_content,
    images,
    tags
)
SELECT 
    w.work_id,
    w.work_title,
    CASE 
        WHEN w.creator_nickname = '作家小W' THEN 
            '霍格沃茨特快列车缓缓驶入车站，哈利、罗恩和赫敏终于回到了他们最爱的魔法学校。站台上飘着薄薄的雾气，若隐若现的城堡轮廓显得格外神秘...'
        WHEN w.creator_nickname = '画师小A' THEN 
            '【图片1】清晨的魁地奇球场：哈利和德拉科在晨雾中对峙\n【图片2】图书馆一角：赫敏专注看书的背影\n【图片3】魔药教室：坩埚冒着彩色烟雾'
        WHEN w.creator_nickname = '翻译小T' THEN
            '迷情剂的制作方法：\n1. 月光下采集的玫瑰花瓣\n2. 薄荷叶的精华\n3. 独角兽的鬃毛...\n\n注意事项：调制时需要在满月之夜，同时保持坩埚温度恒定...'
        WHEN w.creator_nickname = '爱读书的小R' THEN
            '每个人的守护神都是独特的，它们反映了施咒者最深层的品格和情感。哈利的牡鹿继承自他父亲，卢娜的兔子轻盈可爱，而纳威的守护神...'
    END,
    '{"version": 1}'::jsonb,
    CASE 
        WHEN w.creator_nickname = '画师小A' THEN 
            ARRAY[
                'https://example.com/hp/quidditch_morning.jpg',
                'https://example.com/hp/library_hermione.jpg',
                'https://example.com/hp/potion_class.jpg'
            ]
        ELSE ARRAY[]::TEXT[]
    END,
    ARRAY(
        SELECT t.id 
        FROM tag_ids t 
        WHERE t.name = ANY(
            CASE w.creator_nickname
                WHEN '作家小W' THEN ARRAY['魔法', '霍格沃茨', '友情', '冒险', '连载']
                WHEN '画师小A' THEN ARRAY['魁地奇', '霍格沃茨', '日常', '插画']
                WHEN '翻译小T' THEN ARRAY['魔药', '霍格沃茨', '教学']
                WHEN '爱读书的小R' THEN ARRAY['守护神', '治愈', '成长', '连载']
            END
        )
    )
FROM work_info w;

-- Insert chat messages
WITH users AS (
    SELECT ub.user_id, ub.nickname, au.email
    FROM public.user_basic ub
    JOIN auth.users au ON ub.user_id = au.id
    WHERE ub.nickname IN ('画师小A', '爱读书的小R', '编辑小E', '翻译小T', '评论家小V', '作家小W')
)
INSERT INTO public.chat (seq_id, from_user_id, to_user_id, content, is_read)
SELECT 
    ROW_NUMBER() OVER (ORDER BY msg.timestamp) as seq_id,
    sender.user_id as from_user_id,
    receiver.user_id as to_user_id,
    msg.content,
    msg.is_read
FROM (
    VALUES 
        -- 作家和画师的合作对话
        ('作家小W', '画师小A', '2025-05-07 10:00:00', 
         '{"type": "text", "content": "你好！看了你的《魔法世界的日常》插画集，画风非常棒！有兴趣为我的《霍格沃茨的新学期》创作一些插图吗？"}'::jsonb, 
         true),
        ('画师小A', '作家小W', '2025-05-07 10:15:00',
         '{"type": "text", "content": "谢谢夸奖！我很感兴趣，正好最近在练习魔法场景的构图。你有什么具体想法吗？"}'::jsonb,
         true),
        
        -- 编辑和作家的讨论
        ('编辑小E', '作家小W', '2025-05-07 11:00:00',
         '{"type": "text", "content": "新作品的开头非常吸引人！建议可以多描写一下新转学生的背景故事，增加悬疑感。"}'::jsonb,
         true),
        ('作家小W', '编辑小E', '2025-05-07 11:30:00',
         '{"type": "text", "content": "感谢建议！我正在构思这个角色，想把他设定成一个来自德姆斯特朗的交换生。"}'::jsonb,
         true),
        
        -- 读者和作家的互动
        ('爱读书的小R', '作家小W', '2025-05-07 14:00:00',
         '{"type": "text", "content": "太期待新作品的后续了！霍格沃茨的转学生这个设定很新颖，让我想到了三强争霸赛。"}'::jsonb,
         false),
        ('作家小W', '爱读书的小R', '2025-05-07 14:20:00',
         '{"type": "text", "content": "谢谢支持！确实有参考三强争霸赛的元素，不过这次的故事会更侧重校园日常和友情。"}'::jsonb,
         true),
        
        -- 翻译和评论家的交流
        ('翻译小T', '评论家小V', '2025-05-07 15:00:00',
         '{"type": "text", "content": "最近在翻译一些魔药学相关的内容，想请教你对专业术语翻译的看法。"}'::jsonb,
         true),
        ('评论家小V', '翻译小T', '2025-05-07 15:30:00',
         '{"type": "text", "content": "很高兴你来询问！我建议可以参考原著的官方翻译，保持术语的一致性。要不要语音详细聊聊？"}'::jsonb,
         true),
        
        -- 画师和读者的互动
        ('爱读书的小R', '画师小A', '2025-05-07 16:00:00',
         '{"type": "text", "content": "你画的魁地奇球场晨雾太美了！特别是哈利和德拉科对峙的场景，充满张力！"}'::jsonb,
         true),
        ('画师小A', '爱读书的小R', '2025-05-07 16:15:00',
         '{"type": "text", "content": "谢谢！我特意选择了晨雾来营造氛围，很高兴你能感受到。下次想画一张禁林的场景。"}'::jsonb,
         false),
        
        -- 编辑和翻译的工作交流
        ('编辑小E', '翻译小T', '2025-05-07 17:00:00',
         '{"type": "text", "content": "最近有个关于魔法史的翻译项目，你有兴趣参与吗？内容很有趣。"}'::jsonb,
         true),
        ('翻译小T', '编辑小E', '2025-05-07 17:30:00',
         '{"type": "text", "content": "听起来很棒！我对魔法史很感兴趣。能发一些具体内容给我看看吗？"}'::jsonb,
         true)
) AS msg(sender_nickname, receiver_nickname, timestamp, content, is_read)
JOIN users sender ON sender.nickname = msg.sender_nickname
JOIN users receiver ON receiver.nickname = msg.receiver_nickname
ORDER BY msg.timestamp;
