export enum ErrCode {
  SUCCESS = 0,

  DB_ERROR = -1000,

  UNAUTHORIZED = -1001,
  INVALID_PARAM = -1002,
}


/**
 * PostgREST错误代码枚举
 * 对应PostgREST服务返回的标准错误代码
 */
export enum PostgresErrorCode {
  // 1xx - 客户端错误
  INVALID_ACCEPT_HEADER = 'PGRST100',
  INVALID_CONTENT_TYPE = 'PGRST101',
  INVALID_REQUEST_BODY = 'PGRST102',
  INVALID_QUERY_PARAM = 'PGRST103',
  UNSUPPORTED_HTTP_METHOD = 'PGRST104',
  INVALID_SCHEMA_OR_TABLE = 'PGRST105',
  MISSING_REQUIRED_PARAM = 'PGRST106',
  INVALID_JWT_SIGNATURE = 'PGRST107',
  EXPIRED_JWT_TOKEN = 'PGRST108',
  MISSING_AUTHORIZATION_HEADER = 'PGRST109',
  UNSUPPORTED_JWT_ALGORITHM = 'PGRST110',
  INVALID_ROLE_CLAIM = 'PGRST111',
  URI_TOO_LONG = 'PGRST112',
  CONFLICTING_QUERY_PARAMS = 'PGRST113',
  INVALID_SORT_PARAM = 'PGRST114',
  RESOURCE_NOT_FOUND = 'PGRST115',
  SINGLE_ITEM_VIOLATION = 'PGRST116',

  // 2xx - 权限错误
  UNAUTHORIZED_ACCESS = 'PGRST200',
  FORBIDDEN_ACCESS = 'PGRST201',
  ROLE_NOT_FOUND = 'PGRST202',
  ROLE_SWITCH_FAILED = 'PGRST203',

  // 3xx - 服务器内部错误
  DATABASE_CONNECTION_FAILED = 'PGRST300',
  QUERY_EXECUTION_FAILED = 'PGRST301',
  TRANSACTION_FAILED = 'PGRST302',
  PROCEDURE_CALL_FAILED = 'PGRST303',
  DATABASE_TIMEOUT = 'PGRST304',
  OUT_OF_MEMORY = 'PGRST305',
  CONFIGURATION_ERROR = 'PGRST306',

  // 4xx - 资源错误
  RESOURCE_CONFLICT = 'PGRST400',
  RESOURCE_MODIFIED = 'PGRST401',
  RESOURCE_DELETED = 'PGRST402',
  RESOURCE_CREATION_FAILED = 'PGRST403',
  RESOURCE_UPDATE_FAILED = 'PGRST404',
  RESOURCE_DELETION_FAILED = 'PGRST405',

  // 5xx - 响应错误
  RESPONSE_FORMAT_ERROR = 'PGRST500',
  RESPONSE_TOO_LARGE = 'PGRST501',
  CONTENT_NEGOTIATION_FAILED = 'PGRST502',

  // 6xx - 流式处理错误
  STREAMING_QUERY_FAILED = 'PGRST600',
  STREAMING_RESPONSE_INTERRUPTED = 'PGRST601',

  // 7xx - 模式发现错误
  SCHEMA_DISCOVERY_FAILED = 'PGRST700',
  VIEW_DEFINITION_ERROR = 'PGRST701',
  FUNCTION_PARAM_MISMATCH = 'PGRST702',

  // 8xx - 高级特性错误
  WEBSOCKET_CONNECTION_FAILED = 'PGRST800',
  CHANGE_SUBSCRIPTION_FAILED = 'PGRST801',
  BATCH_REQUEST_FAILED = 'PGRST802',
  OPENAPI_GENERATION_FAILED = 'PGRST803',

  // 9xx - 自定义错误
  USER_DEFINED_ERROR = 'PGRST900'
}    
